In [1]:
import pandas as pd
import numpy as np
import faiss
import requests

In [2]:
index = faiss.read_index('index')

In [3]:
df = pd.read_csv('cz_real_estate.csv')

In [4]:
property_of_interest = df[df.location.str.contains('Roztoky u Prahy') & 
   df.title.str.contains('pronájem|pronajem', case=False)]

In [5]:
property_of_interest

,title,price,currency,location,description_en,description_native,construction_of_building,condition,equipped,area_of_property,...,age,garage,elevator,balcony,parking,barrier_free_access,cellar,near_public_transport,terrace,transaction_type
8057,Pronájem domu 3+1 • 70 m² bez realitky Za poto...,30000.0,CZK,"Za potokem, Roztoky - Roztoky u Prahy, Středoč...",I am offering a family house with a layout of ...,Nabízím k pronájmu rodinný dům o dispozici 3+1...,Smíšená,Dobrý,Částečně,600.0,...,NaN,0,0,0,1,0,1,0,0,rent

In [6]:
def create_textual_representation(row):
    textual_representation = f""" Title: {row["title"]},
Price: {row["price"]} {row["currency"]},

Description_in_native: {row["description_native"]},

Description_in_english: {row["description_en"]}""" # Let's test these features for now
    return textual_representation

In [7]:
df['textual_representation'] = df.apply(create_textual_representation, axis=1)
representation = df['textual_representation'].iloc[8057]

In [8]:
type(representation)

str

In [9]:
res = requests.post('http://localhost:11434/api/embeddings',
                    json={
                        'model': 'nomic-embed-text',
                        'prompt': representation
                    }
                   )

embedding = np.array([res.json()['embedding']], dtype = 'float32')

D, I = index.search(embedding, 5)

In [10]:
D

array([[ 0.      , 60.108437, 62.599186, 64.89725 , 65.82964 ]],
      dtype=float32)

In [11]:
I

array([[8057, 2434, 3738, 8320, 1771]])

In [12]:
best_matches = np.array(df['textual_representation'])[I.flatten()]

for match in best_matches[1:]: # skip the first (it's identical to the query)
    print('NEXT PROPERTY')
    print(match)
    print()

NEXT PROPERTY
 Title: Pronájem bytu 3+kk • 65 m² bez realitky Palackého třída, Brno - Královo Pole, Jihomoravský kraj,
Price: 10000.0 CZK,

Description_in_native: Nabízíme pokoj v RD v Králově poli.
Jedná se o samostatný pokoj v 1. patře rodinného domu. Na patře se dále nachází další dva pokoje a dva spolubydlící se kterými je společná kuchyň a koupelna. Na bytě se nachází pračka, ale pokoj je nevybavený. Celý dům nedávno prošel rekonstrukcí, takže vše to tam ještě voní novotou.
K dispozici je také prostorná nádherná terasa, která přímo vybízí k odpočinku.
Dům se nachází v klidné lokalitě ale zároveň 2 min chůze od zastávky MHD a 10 min do centra.
V případě zájmu mě neváhejte kontaktovat.,

Description_in_english: We offer a room in a family house in Královo Pole.
It is an independent room on the first floor of the house. On this floor, there are two more rooms and two housemates with whom the kitchen and bathroom are shared. Although there is a washing machine in the apartment, the room is unfurnished. The entire house has recently been renovated, so everything still has that new, fresh scent.
There is also a spacious, beautiful terrace that directly invites you to relax.
The house is located in a quiet area yet is only a 2-minute walk from a public transportation stop and 10 minutes from the center.
If you are interested, please do not hesitate to contact me.

NEXT PROPERTY
 Title: Prodej domu 7+1 • 166 m² bez realitky Lovčen, Ledeč nad Sázavou - Ledeč nad Sázavou, Kraj Vysočina,
Price: 5999000.0 CZK,

Description_in_native: Investiční dvougenerační dům po rekonstrukci – stabilní výnos, nájemníci zajištěni Nabízím k prodeji cihlový dvougenerační dům v osobním vlastnictví po kompletní rekonstrukci vnitřních prostor, vhodný jako dlouhodobá investice i kombinace bydlení a pronájmu. Dům je rozdělen na dvě samostatné bytové jednotky s oddělenými vstupy: • Horní byt: 3+kk, 76 m² • Spodní byt: 3+1, 90 m² Celková obytná plocha činí 166 m², pozemek má výměru 226 m². Oba byty jsou dlouhodobě pronajaty za celkové nájemné 27 000 Kč měsíčně (bez poplatků). Nájemníci jsou spolehliví, platí řádně a mají zájem v nájmu pokračovat. Výnos z nájmu odpovídá více než 5,4 % ročně, což je v této cenové hladině velmi obtížně nahraditelné. Nemovitost je ve velmi dobrém technickém stavu, po pečlivé rekonstrukci, s důrazem na funkčnost a dlouhodobou udržitelnost. Parkování je možné přímo před domem. Dům se nachází v Ledči nad Sázavou, městě s kompletní občanskou vybaveností. V docházkové vzdálenosti jsou obchody, školy, vlakové i autobusové nádraží. Lokalita nabízí také přírodu, cyklostezky podél řeky Sázavy a historický hrad. Prodej probíhá přímo od majitele, bez provize realitní kanceláře. V případě zájmu o více informací nebo osobní prohlídku mě neváhejte kontaktovat.,

Description_in_english: Investment Two-Generation House After Renovation – Stable Yield, Secured Tenants
I offer for sale a brick two-generation house in personal ownership that has undergone a complete interior renovation, making it suitable as a long-term investment or a combination of living and renting.
The house is divided into two separate residential units with individual entrances:
• Upper apartment: 3+kk, 76 m²
• Lower apartment: 3+1, 90 m²
The total living area is 166 m², and the plot measures 226 m².
Both apartments are rented on a long-term basis for a total rent of CZK 27,000 per month (excluding fees). The tenants are reliable, pay on time, and are interested in continuing the rental. The rental yield amounts to more than 5.4% per year, which is very difficult to match in this price range.
The property is in very good technical condition after careful renovation, with an emphasis on functionality and long-term sustainability. Parking is available directly in front of the house.
The house is located in Ledče nad Sázavou, a town with complete civic amenities. Within walking distance are shops, schools, and both train and bus stations. The area also offers nature, cycling paths along the Sázava River, and a historic castle.
The sale is conducted directly by the owner, with no real estate agency commission.
If you are interested in more information or a personal viewing, please do not hesitate to contact me.

NEXT PROPERTY
 Title: Prodej bytu 3+1 • 68 m² bez realitky Křivsoudov - Křivsoudov, Středočeský kraj,
Price: 3590000.0 CZK,

Description_in_native: Hledáte opravdový domov? Slunný byt 3+1 se zahradou a výhodami rodinného domu
Prodávám jeden ze čtyř bytů v našem bytovém domě v městysi Křivsoudov, který se nachází jen 5 km od sjezdu z dálnice D1. Byt je ideálně vhodný pro mladou rodinu, která si zde chce vybudovat svůj vysněný domov a hledá klidné a úsporné bydlení, které v sobě snoubí výhody bydlení v bytě a rodinném domě - tedy nižší pořizovací cena za byt, nízké náklady na údržbu, ale k tomu vlastní místo na zahradě, parkování, dostatek úložných prostor ve sklepě a vlastní kůlna pro zřízení dílny nebo odložení sezonních věcí.
Tento byt má dispozici 3+1 a podlahovou plochu 67,5 m²
Proč se tu budete cítit jako v rodinném domě? Ke každému bytu totiž patří:
Vlastní kousek zahrady o rozloze zhruba 75 m² – ideální místo na pískoviště, letní grilovačku nebo vlastní záhonky.
Velkorysý a uzamykatelný prostor v zahradní kůlně (cca 16 m²) na kola, kočárek, lyže nebo nářadí.
Dvě poctivé zděné kóje ve sklepě pro uskladnění sezónních věcí.
Parkovací místo na pozemku domu s přípravou na přivedení nabíječky elektromobilu (rozvaděč ve sklepě s podružným měřením a vyvedený kabel k patě domu).
Dům je poctivě zrekonstruovaný a připravený na budoucnost:
Během uplynulého roku prošel celý dům opravdu rozsáhlou a pečlivou rekonstrukcí. Nešetřilo se na něm:
Je kompletně zateplený – na fasádě je 20 cm šedého polystyrenu a sokly jsou zateplené 16 cm XPS až po úroveň základů.
Všude jsou nová kvalitní okna a dveře s izolačními trojskly.
O teplo se stará moderní tepelné čerpadlo vzduch/voda , díky kterému jsou náklady na vytápění extrémně nízké (v minulé topné sezóně to bylo 9 500 Kč za byt na celý rok).
Myslelo se i na budoucí technologie – dům má hotovou přípravu na fotovoltaiku a k parkovacímu místu si můžete snadno dopojit nabíječku na elektromobil.
Byt bude uvolněný a připravený k předání v březnu. Prodávám ho v původním stavu, určený k rekonstrukci. Fotografie přiložené k inzerátu jsou vizualizace, které vám mohou posloužit jako inspirace, jak krásný a moderní prostor se z něj dá vytvořit.
Nabízená cena odpovídá současnému stavu před rekonstrukcí. Zohledňuje nákladnou rekonstrukci celého domu a ponechává volnost novým majitelům si byt zařídit podle vlastních představ. Pokud byste ale chtěli ušetřit čas a starosti, můžeme se domluvit a část rekonstrukčních prací vám mohu po dohodě zajistit (což by se následně promítlo v kupní ceně).
Prodávám napřímo, takže neplatíte žádnou provizi realitní kanceláři.
V případě zájmu mě neváhejte kontaktovat skrze zprávy na komunikační platformě.,

Description_in_english: Are you looking for a true home? A bright 3+1 apartment with a garden and all the benefits of a family house
I am selling one of the four apartments in our residential building in the small town of Křivsoudov, located just 5 km from the D1 highway exit. This apartment is ideally suited for a young family looking to build their dream home in a peaceful and affordable living environment that combines the advantages of apartment living and a family house – that is, a lower purchase price, low maintenance costs, plus your own garden space, parking, ample storage in the cellar, and a dedicated shed for a workshop or storing seasonal items.
This apartment is laid out as a 3+1 with a floor area of 67.5 m².
Why will you feel like you’re in a family house here? Each apartment comes with:
• Its own garden plot of approximately 75 m² – an ideal spot for a sandbox, a summer barbecue, or your own flower beds.
• A generous, lockable space in the garden shed (about 16 m²) for bikes, a stroller, skis, or tools.
• Two solid brick storage rooms in the cellar for storing seasonal items.
• A parking space on the property with the provision for connecting an electric car charger (distribution board in the cellar with sub-metering and a cable led to the entrance of the house).
The building has been thoroughly renovated and is ready for the future:
Over the past year, the entire building underwent extensive and careful renovation. No expense was spared:
• It is completely insulated – the facade has 20 cm of grey polystyrene and the plinths are insulated with 16 cm of XPS up to the foundation level.
• New, high-quality windows and doors with insulating triple glazing have been installed throughout.
• A modern air-to-water heat pump takes care of the heating, keeping heating costs extremely low (in the last heating season, it was 9,500 CZK per apartment for the entire year).
• Future technologies were also considered – the house is pre-wired for photovoltaic panels, and you can easily connect an electric car charger to your parking space.
The apartment will be vacated and ready to hand over in March. I am selling it in its original state, meant for renovation. The photographs attached to the advertisement are visualizations that can serve as inspiration for how beautiful and modern the space can be transformed.
The asking price reflects the current state before renovation. It takes into account the costly renovation of the entire building and leaves new owners the freedom to design the apartment to their own taste. However, if you would like to save time and hassle, we can come to an agreement, and I can arrange some of the renovation work (which would then be reflected in the purchase price).
I am selling directly, so you do not pay any real estate agency commission.
If you are interested, please feel free to contact me through messages on the communication platform.

NEXT PROPERTY
 Title: Prodej bytu 3+kk • 74 m² bez realitky Charkovská, Olomouc - Olomouc-město, Olomoucký kraj,
Price: 6900000.0 CZK,

Description_in_native: Nabízím k prodeji světlý a kompletně zrekonstruovaný byt 3+kk o ploše 74 m², který se nachází ve 4. patře domu bez výtahu (jeho výstavba je plánována). Byt prošel nadstandardní rekonstrukcí: nové betonové podlahy, tvrzené sádrokartonové příčky, kompletně nové rozvody elektřiny a topení ve zdi, nové radiátory, kondenzační kotel, zděné jádro, nová koupelna, WC a kuchyňská linka se spotřebiči. V bytě jsou nová plastová okna.
Součástí je lodžie 2,5 m² orientovaná do klidného vnitrobloku a velký sklep 12 m², který je vhodný pro uskladnění kol, kočárku, lyží a sezónního vybavení nebo může sloužit jako domácí dílna.
Byt je vhodný pro mladou rodinu nebo jako investiční příležitost pro dlouhodobý pronájem. Ložnice jsou orientovány na východ a jihovýchod, kuchyně a lodžie pak do vnitrobloku. Parkování je možné na veřejných plochách v okolí domu.
Občanská vybavenost do 600 m:
V bezprostřední docházkové vzdálenosti se nachází mateřská škola kpt. Nálepky (cca 2 minuty chůze) a základní škola / Moravská střední škola přímo přes ulici. V okolí je tedy několik škol a školek dostupných bezpečnou pěší trasou.
V okruhu do 600 m jsou také potraviny, dětské hřiště, cukrárna, restaurace, bankomat, pošta a lékárna. Lokalita nabízí veškeré služby potřebné pro každodenní život.
Dostupnost:
Centrum města je vzdáleno přibližně 10–12 minut chůze. Hlavní nádraží Olomouc je asi 1,4 km od domu, tedy přibližně 5 minut MHD nebo 15–17 minut pěšky. Zastávky MHD Pasteurova (199 m) a U Bystřičky (316 m) jsou v blízkosti domu.,

Description_in_english: I am offering a bright and fully renovated 3-room apartment (3+kk) with a total floor area of 74 m², located on the 4th floor of a residential building without an elevator (its construction is planned). The apartment has undergone a complete, high-quality renovation including new concrete floors, reinforced plasterboard partition walls, entirely new electrical and heating installations embedded in the walls, new radiators, a modern condensing boiler, a rebuilt brick-core bathroom, new WC, and a fully equipped custom kitchen. The apartment is fitted with new plastic windows.
The property includes a 2.5 m² loggia facing a quiet courtyard and a spacious 12 m² storage room, suitable for storing bicycles, strollers, skis, and seasonal equipment, or it can be used as a home workshop.
The apartment is suitable for a young family or as an excellent investment for long-term rental. The bedrooms are oriented to the east and southeast, while the kitchen and loggia face the courtyard. Public parking is available around the building.
Amenities within 600 metres:
Within a short walking distance, you will find the Kpt. Nálepky kindergarten (approx. 2 minutes on foot) and a primary school / Moravian Secondary School directly across the street. There are several nurseries and schools in the immediate vicinity, all accessible safely on foot.
Within the same radius, you will also find grocery shops, a children’s playground, a café, restaurants, an ATM, a post office, and a pharmacy. The location offers all essential daily services within easy reach.
Transport and accessibility:
The city centre is approximately a 10–12 minute walk away. Olomouc Main Train Station is located about 1.4 km from the property — roughly 5 minutes by public transport or 15–17 minutes on foot. Public transport stops Pasteurova (199 m) and U Bystřičky (316 m) are located nearby.

# Discussion
It seems that we are getting random recommendations.
Let's try to change query and see if the matches will be close.

## Different country

In [13]:
property_of_interest = df[df.location.str.contains('Berlin') &
  df.title.str.contains('pronájem|pronajem', case=False)]
property_of_interest.iloc[:5]

,title,price,currency,location,description_en,description_native,construction_of_building,condition,equipped,area_of_property,...,garage,elevator,balcony,parking,barrier_free_access,cellar,near_public_transport,terrace,transaction_type,textual_representation
36,Inzerát již není v nabídce Pronájem bytu 2+1 •...,1813.0,EUR,Berlin Mitte Berlin 10119,NaN,Tento atraktivní 2-pokojový byt s přibližně 70...,NaN,Po rekonstrukci,NaN,NaN,...,0,1,0,0,0,0,1,0,rent,Title: Inzerát již není v nabídce Pronájem by...
175,Pronájem bytu 2+1 • 55 m² bez realitky Einödsh...,1600.0,EUR,Einödshofer Weg Berlin Mariendorf Berlin 12109,NaN,Tento vysoce kvalitní podkrovní byt v 5. patře...,NaN,Po rekonstrukci,Vybaveno,NaN,...,0,0,1,0,0,1,1,0,rent,Title: Pronájem bytu 2+1 • 55 m² bez realitky...
228,Pronájem bytu 3+1 • 76 m² bez realitky Berlin ...,1500.0,EUR,Berlin Frohnau Berlin 13465,NaN,Tento 3-pokojový byt o přibližně 75 m² obytné ...,NaN,NaN,NaN,NaN,...,1,0,1,0,0,1,1,0,rent,Title: Pronájem bytu 3+1 • 76 m² bez realitky...
255,Pronájem bytu • 74 m² bez realitky Grünauer St...,550.0,EUR,Grünauer Straße 54 Berlin Köpenick Berlin 12557,NaN,Světlý a moderně vybavený byt v prvním patře b...,NaN,NaN,Vybaveno,NaN,...,0,0,1,0,0,1,1,0,rent,Title: Pronájem bytu • 74 m² bez realitky Grü...
358,Pronájem bytu 2+1 • 48 m² bez realitky Gélieus...,1200.0,EUR,Gélieustraße 7a Berlin Lichterfelde Berlin 12203,NaN,ZÁKLADNÍ NÁKRES NENÍ VHODNÝ PRO SDÍLENÉ BYDLET...,NaN,Po rekonstrukci,NaN,NaN,...,0,1,1,0,0,1,1,1,rent,Title: Pronájem bytu 2+1 • 48 m² bez realitky...

In [14]:
df['textual_representation'] = df.apply(create_textual_representation, axis=1)
representation = df['textual_representation'].iloc[36]

res = requests.post('http://localhost:11434/api/embeddings',
                    json={
                        'model': 'nomic-embed-text',
                        'prompt': representation
                    }
                   )

embedding = np.array([res.json()['embedding']], dtype = 'float32')

D, I = index.search(embedding, 5)

best_matches = np.array(df['textual_representation'])[I.flatten()]

for match in best_matches[1:]: # skip the first (it's identical to the query)
    print('NEXT PROPERTY')
    print(match)
    print()

NEXT PROPERTY
 Title: Pronájem bytu 3+1 • 68 m² bez realitky Parkstrasse 3, , Hessen,
Price: 1290.0 EUR,

Description_in_native: Tato exkluzivní 3-pokojová bytová jednotka s přibližně 68 m² obytné plochy se nachází ve 2. patře udržovaného činžovního domu ve velmi centrální lokalitě v Bad Vilbel. Byt je k dispozici od 1. března 2026. Bydlení projde kompletní rekonstrukcí a díky svému prvotřídnímu interiérovému řešení nabízí příjemné bydlení. Byt je pronajímán nezařízený.
Bad Vilbel, známý jako lázeňské město, nabízí atraktivní lokalitu k bydlení s dobrou infrastrukturou. Město disponuje řadou nákupních možností, lékařskou péčí a restauracemi. Veřejná doprava je dobře zajištěna, s pravidelnými spoji do okolních měst i do Frankfurtu. Parky a zelené plochy lákají k relaxaci a poskytují řadu volnočasových aktivit.
Infrastruktura (v okruhu 5 km):
Lékárna, diskont potravin, praktický lékař, mateřská škola, základní škola, Hauptschule, Realschule, gymnázium, Gesamtschule, veřejná doprava
Byt bude předán čerstvě zrekonstruovaný. Parkety byly obnoveny, stěny nově natřeny, koupelna a kuchyně zařízeny novým vybavením. Byt je pronajímán nezařízený.,

Description_in_english: nan

NEXT PROPERTY
 Title: Pronájem bytu 2+1 • 56 m² bez realitky Parkstrasse 3, , Hessen,
Price: 1090.0 EUR,

Description_in_native: Tento exkluzivní 2+kk byt s přibližně 56 m² obytné plochy se nachází ve 2. patře udržovaného mnohostanového domu v centrální lokalitě v Bad Vilbelu. Byt bude k dispozici od 1. března 2026. Byt je kompletně rekonstruován a díky své vyspělé interiérové výzdobě nabízí příjemné obytné prostředí. Byt se pronajímá bez nábytku.
Bad Vilbel, známý jako lázeňské město, nabízí atraktivní obytné prostředí s dobrou infrastrukturou. Město disponuje řadou obchodů, lékaři a restauracemi. Veřejná doprava je dostupná s pravidelnými spoji do okolních měst a do Frankfurtu. Parky a zelené plochy lákají k odpočinku a poskytují řadu volnočasových aktivit.
Infrastruktura (v okruhu 5 km):
Lékárna, diskont potravin, praktický lékař, mateřská škola, základní škola, střední škola, gymnázium, integrovaná škola, veřejná doprava
Byt je předán čerstvě zrekonstruovaný. Parkety byly ošetřeny, stěny nově natřeny, nová koupelna a kuchyň. Byt se pronajímá bez nábytku.,

Description_in_english: nan

NEXT PROPERTY
 Title: Pronájem bytu 2+1 • 90 m² bez realitky , Bádensko-Württembersko,
Price: 900.0 EUR,

Description_in_native: Tato světlá 2,5-pokojová maisonette bytu o přibližně 90 m² obytné plochy se nachází ve 2. a 3. patře okouzlující budovy DUPLEX ve Wehru. Byt disponuje krytým balkonem a garáží, což zvyšuje komfort bydlení. Je vybaven zabudovanou kuchyní a vlastním sklepním prostorem, který nabízí dodatečné úložné možnosti. K dispozici je také vlastní využitelná zahrada, která zve k odpočinku. Byt bude k dispozici od 1. února 2026. Domácí mazlíčci nejsou povoleni.
Náklady na vytápění nejsou zahrnuty v provozních nákladech a jsou účtovány zvlášť poskytovatelem nájemci (plynové podlažní topení).
V případě zájmu zašlete prosím krátké osobní sdělení. Pokud budou údaje neúplné, nebude vám poskytnuta zpětná vazba. Pro čtyři osoby není byt vhodný, proto se o něj prosím nezajímejte.
Do sdělení prosím uveďte následující informace:
– Jména a věk všech osob, které budou bydlet v bytě
– Aktuální bydliště
– Proč máte o byt zájem
– Informace o zaměstnavateli a doklad o trvalé pracovní smlouvě
– Přibližný měsíční příjem (čistý)
Wehr nabízí dobrou infrastrukturu s možnostmi nákupu a službami každodenní potřeby. Veřejná doprava je velmi dobře dostupná (autobusová zastávka naproti), což usnadňuje dojezd. Okolí zve k volnočasovým aktivitám venku a poskytuje příjemnou atmosféru pro bydlení.
Obytná plocha ve 2. patře činí cca 62 m² a je rozdělena na:
• Jeden obývací pokoj s laminátovou podlahou v dřevěném vzhledu
• Jednu koupelnu s vanou, sprchou a toaletou
• Jednu kuchyň se zabudovanou kuchyňskou linkou
Obytná plocha ve 3. patře činí cca 28 m² a je rozdělena na:
• Jednu velkou ložnici (kterou lze rozdělit a využít také jako samostatnou kancelář)
Kromě toho byt disponuje:
• Nádherným výhledem skrze zasklenou štítovou část do jižního Schwarzwaldu
• Vlastním sklepem
• Vlastní garáží
• Vlastním trávníkem či zelenou plochou vedle garáže
• Vlastním krytým balkonem s večerním sluncem (cca 10 m², částečně zahrnuto v obytné ploše)
• Plynovým podlažním topením
• Podlahovým topením,

Description_in_english: nan

NEXT PROPERTY
 Title: Prodej bytu 2+1 • 65 m² bez realitky , Bádensko-Württembersko,
Price: 391000.0 EUR,

Description_in_native: Tento bezbariérový 2-pokojový přízemní byt o přibližně 65 m² obytné plochy se nachází v pečlivě udržovaném vícebytovém domě v Umkirchu. Byt nabízí vlastní malou zahradu a přímý přístup do společné zahrady, takže si můžete užívat příjemnou atmosféru bydlení na čerstvém vzduchu. V domě je k dispozici výtah, který usnadňuje přístup do všech pater, a vlastní parkovací místo v garáži zajišťuje pohodlné parkování. Byt je vybaven běžnou vnitřní výbavou a má zařízenou kuchyň i koupelnu. Dále disponuje sklepem, který poskytuje dodatečný úložný prostor. Byt je momentálně trvale pronajatý, což z něj činí i vynikající investiční příležitost.
Umkirch, nacházející se v okrese Breisgau-Hochschwarzwald, nabízí dobrou infrastrukturu s možnostmi každodenního nakupování, lékaři a lékárnami. Veřejnou dopravu zajišťují místní autobusové linky, které spojují s okolními městy a obcemi, včetně Freiburgu. Blízkost rekreačních oblastí a rodinně přátelské prostředí činí z Umkirchu atraktivní místo k bydlení.
Elektrické rolety, optický internet, dvě velmi prostorná parkovací místa v podzemní garáži (vedle sebe).,

Description_in_english: nan

In [15]:
df['textual_representation'] = df.apply(create_textual_representation, axis=1)
representation = df['textual_representation'].iloc[358]

res = requests.post('http://localhost:11434/api/embeddings',
                    json={
                        'model': 'nomic-embed-text',
                        'prompt': representation
                    }
                   )

embedding = np.array([res.json()['embedding']], dtype = 'float32')

D, I = index.search(embedding, 5)

best_matches = np.array(df['textual_representation'])[I.flatten()]

for match in best_matches[1:]: # skip the first (it's identical to the query)
    print('NEXT PROPERTY')
    print(match)
    print()

NEXT PROPERTY
 Title: Pronájem bytu 2+1 • 55 m² bez realitky Čapkova, Karviná - Karviná-město, Moravskoslezský kraj,
Price: 7450.0 CZK,

Description_in_native: Nabízíme k pronájmu exkluzivní byt po kompletní rekonstrukci, který se nachází ve čtvrtém patře cihlového domu bez výtahu, přímo naproti parku. Tento světlý a stylový byt je jako stvořený pro mladý pár, který hledá moderní bydlení s výbornou dostupností i atmosférou. Dominantou bytu je hlavní pokoj s francouzským oknem a přímým vstupem na balkon, odkud si můžete vychutnávat klidný výhled do zeleně. V celém bytě jsou položeny kvalitní plovoucí podlahy, které dodávají prostoru elegantní a čistý vzhled. Kuchyně je vybavena moderní kuchyňskou linkou a nabízí dostatek místa na další vybavení podle vašich potřeb. Praktickým bonusem je komora s přípojkou na pračku, ideální jako prádelna nebo úložný prostor. Koupelna je vybavena vanou, toaleta je oddělená – což přináší větší komfort každodenního bydlení. V chodbě je prostor pro šatní skříň nebo úložný systém. Dům se nachází nad komerčními prostory, kde najdete kadeřnictví, obchody a další služby doslova pod nosem. Tento byt kombinuje styl, pohodlí a skvělou polohu – perfektní volba pro ty, kdo chtějí žít moderně, ale zároveň s nádechem klidu a zeleně.,

Description_in_english: nan

NEXT PROPERTY
 Title: Pronájem bytu 2+1 • 59 m² bez realitky Eichenau Eichenau Bayern 82223,
Price: 1390.0 EUR,

Description_in_native: Tento světlý a upravený 2-pokojový byt zaujme promyšleným dispozicemi, prostornými místnostmi a příjemnou bytovou atmosférou. Byt se nachází v domě s více byty v klidné lokalitě Eichenau a je ideální pro jednotlivce či páry.
Zvláště vyniká velký balkon, který nabízí pěkný výhled do zeleně a spoustu místa pro relaxaci, stolování nebo odpočinek po náročném dni. Díky velkým okenním plochám jsou místnosti prosvětlené, působí prostorně a přívětivě.
Byt je ve velmi dobrém stavu a bude k nastěhování k dispozici od 01.05.2026.
Eichenau patří mezi oblíbené obytné lokality na západ od Mnichova a nabízí výbornou infrastrukturu:
obchody, lékárny, ordinace, školky a školy jsou v bezprostřední blízkosti. Stanice S-Bahn Eichenau (S4) je snadno dostupná a nabízí rychlé spojení do Mnichova i okolních obcí.
Kombinace klidu, zeleně a dobré dopravní dostupnosti činí tuto oblast obzvláště atraktivní pro dojíždějící pracovníky a všechny, kteří chtějí žít blízko přírody, aniž by museli obětovat pohodlnou dostupnost.
2 prostorně řešené místnosti s různými možnostmi využití
Prosvětlené, velké místnosti díky rozsáhlým okenním plochám
Vestavěná kuchyň
Velký balkon s výhledem do zeleně
Koupelna s vanou
Skříňové kóje/kellér pro dodatečné úložné prostory
Upravený celkový stav
Klidné okolí a příjemné bytové prostředí,

Description_in_english: nan

NEXT PROPERTY
 Title: Pronájem bytu 2+1 • 68 m² bez realitky Offenbachstr. 4 Bonn Rüngsdorf Nordrhein-Westfalen 53173,
Price: 1190.0 EUR,

Description_in_native: Tento okouzlující 2-pokojový byt v přízemí zaujme svou promyšlenou dispozicí a příjemnou atmosférou bydlení. Slunná terasa s výhledem do zeleně láká k odpočinku a posezení.
Byt je plně zařízený, takže je ihned k nastěhování – ideální pro jednotlivce, páry nebo dojíždějící pracovníky, kteří ocení komfortní bydlení v klidném prostředí.
Byt se nachází v žádané bonnské čtvrti Bad Godesberg. Poloha zaujme svou klidnou, zavedenou obytnou zónou a zároveň vynikající infrastrukturou.
Centrum Bad Godesbergu s pěší zónou, pestrou nabídkou obchodů, kaváren, restaurací a také lékařů a lékáren je dosažitelné během několika minut.
Doprava veřejnou dopravou je výborně zajištěná. Autobusové a vlakové spoje umožňují rychlý přístup do centra Bonnu i do okolních městských částí. Také dálnice směřující do Kolína nad Rýnem a Koblenze jsou pohodlně dostupné.
Byt disponuje dvěma prostorně řešenými pokoji, přičemž obytná a ložnicová část jsou jasně oddělené. Samostatná kuchyň je od bytu oddělena, což umožňuje příjemné a funkční členění prostoru.
Ve všech obytných prostorech je položen kvalitní parket, zatímco kuchyň a koupelna jsou vybaveny snadno udržovatelnými dlaždicemi.
Koupelna, kterou byly před několika lety modernizovány, okouzlí bezbariérovou sprchou a současným vybavením. Praktická komora uvnitř bytu nabízí dodatečný úložný prostor.
Byt je plně zařízený a umožňuje okamžité nastěhování. Pronájem je sjednán na dobu určitou, maximálně na tři roky – ideální pro ty, kteří hledají komfortní dočasné řešení bydlení.,

Description_in_english: nan

NEXT PROPERTY
 Title: Pronájem bytu 2+1 • 47 m² bez realitky , Šlesvicko-Holštýnsko,
Price: 680.0 EUR,

Description_in_native: Tento udržovaný 2-pokojový byt o přibližně 46,4 m² obytné plochy se nachází v prvním patře moderního bytového domu z roku 2003 v Bargteheide. Byt disponuje světlým obývacím pokojem, ložnicí, kuchyní vybavenou elektrickým sporákem, troubou a lednicí a prostornou koupelnou se sprchou. Zvláštním lákadlem je balkon, který vybízí k odpočinku. K dispozici je také sklep, který nabízí další úložný prostor. Typ vytápění je centrální plynové topení. Byt bude k dispozici od 1. 4. 2026.
S ohledem na soukromí stávajícího nájemce se na fotografiích z bytu neobjevily žádné snímky. Při prohlídce bytu se můžete přesvědčit o moderním charakteru a kvalitě tohoto bytu.
Zobrazený půdorys slouží pouze jako orientační zobrazení nájemního bytu; drobné odchylky od skutečných prostorových dispozic jsou možné.
Bargteheide nabízí kvalitní infrastrukturu s možnostmi nákupů, lékaři a školami v blízkém okolí. Vynikající napojení na veřejnou dopravu usnadňuje dojíždění. Okolí láká k volnočasovým aktivitám v přírodě a nabízí příjemnou kvalitu bydlení v okolí Hamburku.,

Description_in_english: nan

In [16]:
df['textual_representation'] = df.apply(create_textual_representation, axis=1)
representation = df['textual_representation'].iloc[175]

res = requests.post('http://localhost:11434/api/embeddings',
                    json={
                        'model': 'nomic-embed-text',
                        'prompt': representation
                    }
                   )

embedding = np.array([res.json()['embedding']], dtype = 'float32')

D, I = index.search(embedding, 5)

best_matches = np.array(df['textual_representation'])[I.flatten()]

for match in best_matches[1:]: # skip the first (it's identical to the query)
    print('NEXT PROPERTY')
    print(match)
    print()

NEXT PROPERTY
 Title: Pronájem bytu 5+1 • 155 m² bez realitky Merseburger Str. 406 Halle/Saale Ammendorf Sachsen-Anhalt 06132,
Price: 1850.0 EUR,

Description_in_native: Prostorný a plně zařízený 5-pokojový byt s obytnou plochou 155 m² nabízí ideální podmínky pro montéry, pracovníky na dohodu, expaty nebo pro společné bydlení.
Byt se nachází v Halle-Ammendorfu a vyniká skvělou dopravní dostupností do Halle i do Schkeuditzu směrem k DHL Hub.
5-pokojový byt se nachází v Halle-Ammendorfu, v klidné rezidenční oblasti s rychlým spojením. Možnost nakupování je v bezprostřední blízkosti.
Lokalita nabízí velmi dobrou dostupnost do Halle, do Schkeuditzu (například ke DHL Hub) a do Merseburgu.
Jsou k dispozici další parkovací místa pro automobily.
5 prostorných místností – flexibilně využitelných jako ložnice, pracovny či společné prostory, až s možností ubytovat 8 postelí.
2 moderní koupelny – jedna s vanou, druhá se sprchou, obě s vlastní pračkou.
Vestavěná kuchyň – plně vybavená pro okamžité nastěhování, včetně 2 lednic.
Plně zařízeno – nastěhujte se ihned a budete se cítit jako doma:
• Ve 4 ložnicích najdete: postel, pracovní stůl se židlí, skříň, policový systém, stojací lampu s USB hubem.
• V obývacím pokoji je: posezení, pohovka, nábytek pod televizi včetně televizoru a stůl.
• Koupelny jsou vybaveny regálem a věšáky, pračkou a úložnými prostory.
Vhodné pro spolubydlení – ideální pro studenty nebo pracující.
Možnosti zatemnění oken – ideální pro pracovníky na směny, kteří potřebují i přes den kvalitní spánek.
Internet s rychlostí 250 Mbit/s je k dispozici za 50,- €/měsíc.
Podmínky:
• Základní nájem: 1.850,- €
• Základní provozní náklady: 150,- €
• Smlouvy na plyn a elektřinu musí být uzavřeny nájemcem samostatně s dodavatelem, případně je možné sjednat paušál přes pronajímatele.
• Všechny částky jsou uvedeny bez DPH, takže celkový nájem činí 2.380,- €.
Možnost využít externí úklidovou firmu.
K dispozici ihned / od 01.01.26
Pronájem na dobu určitou je možný, minimální doba nájmu je 6 měsíců.
Máte zájem?
Neváhejte nás kontaktovat pro domluvení prohlídky.,

Description_in_english: nan

NEXT PROPERTY
 Title: Pronájem bytu 5+1 • 150 m² bez realitky Freising Freising Bayern 85356,
Price: 3300.0 EUR,

Description_in_native: Kompletně zařízený a ihned k nastěhování připravený 5-pokojový byt v přízemí s vlastním zahradním prostorem ve Freisingu (85356). Nájemné all-inclusive.
Pouze cca 15 minut od letiště v Mnichově, rychlé spojení do Mnichova a okolí.
Ideální pro projektové pracovníky, expaty, firemní zákazníky nebo rodiny hledající kvalitní a plně vybavené ubytování.
Další fotografie na vyžádání.
Detaily:
– cca 150,5 m² obytné plochy v přízemí
– navíc cca 74 m² zrekonstruovaného sklepení
– 4 samostatné ložnice s téměř novými čalouněnými postelemi
– prostorný obývací a jídelní pokoj
– jižní terasa a zahrada
– vysoce kvalitní designová vestavěná kuchyň včetně elektrospotřebičů a kompletního vybavení kuchyně
– koupelna se sprchou a vanou
– další toaleta pro hosty
– samostatná garáž v domě s přímým přístupem do bytu
– dvě další venkovní parkovací místa
Byt se nachází v příjemné, klidné obytné čtvrti v okrese Freising (PSČ 85356). Centrum Freisingu je dosažitelné za několik minut a nabízí vše potřebné pro každodenní život – od obchodů přes restaurace až po lékaře, školy a mateřské školky.
Okolí je charakterizováno upravenou zástavbou a vyspělým obytným prostředím, které je atraktivní jak pro rodiny, tak pro pracující. V bezprostřední blízkosti se nacházejí zelené plochy a možnosti volnočasových aktivit, které vás zvou k procházkám nebo odpočinku.
Zastávka autobusu přímo v blízkosti zajišťuje pohodlné spojení do centra Freisingu a na nádraží. Automobilově se dostanete do Freisingu za krátkou dobu, na letiště v Mnichově za cca 15 minut a do centra Mnichova za přibližně 40 minut. Přes B301 je rovněž rychlé spojení na dálnici A92.
Lokalita tak nabízí vyváženou kombinaci klidu, dobré infrastruktury a optimální dostupnosti – ideální pro všechny, kteří chtějí bydlet v klidu a přitom zůstat flexibilní.
Vybavení:
– 55-palcová chytrá TV
– vysokorychlostní internet
– pračka a sušička
– na osobu dvě sady povlečení a ručníky a koupelnové ručníky
– plné kuchyňské vybavení (nádobí, hrnce, mikrovlnná trouba atd.)
– společné prostory jsou uklízeny každý 14. den a při odchodu je provedena závěrečná úklidová služba
Uvedené nájemné zahrnuje paušální náklady. Ty zahrnují všechny poplatky za energie, internet a poplatek za rozhlasové vysílání. Elektřina si zařizuje nájemník samostatně a je účtována zvlášť. Nebudou prováděny žádné samostatné vyúčtování provozních nákladů.,

Description_in_english: nan

NEXT PROPERTY
 Title: Pronájem bytu 2+1 • 54 m² bez realitky Berliner Str 26, , Hessen,
Price: 1300.0 EUR,

Description_in_native: Od 15.3.26 je k pronájmu čerstvě zrekonstruovaný 2-pokojový byt ve centrální části Bad Homburgu. Byt se nachází na Berliner Straße 26 a nabízí přibližně 54 m² obytné plochy.
Vybavení:
• Byt je kompletně zařízený.
• Prostorný obývací pokoj spojený s ložnicí.
• Podlahy z masivního dřeva a čerstvě natřené stěny.
• Nová koupelna se sprchou.
• Samostatná kuchyně se všemi potřebnými spotřebiči.
• Balkón s nádherným výhledem.
• Úložný prostor ve sklepu.
Nájemné včetně provozních nákladů: 1 600 €
K nastěhování: ihned
Energetický průkaz je k dispozici.
Kontakt:
V případě zájmu nebo pro sjednání prohlídky nás prosím kontaktujte zprávou nebo telefonicky.
Byt zaujme svou centrální polohou s výborným spojením dopravou veřejnou, ale také možnostmi nákupu, restauracemi a volnočasovými aktivitami v bezprostřední blízkosti. Nádraží je vzdáleno jen pár minut pěšky a letiště ve Frankfurtu je dosažitelné za pouhých 20 minut.
Byt je již kompletně zařízený.,

Description_in_english: nan

NEXT PROPERTY
 Title: Pronájem bytu 2+1 • 63 m² bez realitky , Bádensko-Württembersko,
Price: 790.0 EUR,

Description_in_native: Tento příjemný 2-pokojový byt s přibližně 63 čtverečními metry obytné plochy se nachází v podkroví sedízdílného domu v klidné čtvrti Sandhausen. K nastěhování ihned!
Byt se skládá ze dvou pokojů, kuchyně, koupelny a balkonu. K bytu náleží také sklep, který je součástí pronájmu. Navíc je možné si na vyžádání pronajmout garáž – měsíční nájem za ni činí 50 €.
Více rodinný dům byl pravidelně modernizován a nachází se ve velmi dobrém a udržovaném stavu. Dům se nachází v oblíbené obytné čtvrti Sandhausen, která zaujme svou klidnou atmosférou a blízkostí ke všem důležitým zařízení – nákupním možnostem, školám, mateřským školám a veřejné dopravě. Lokalita navíc nabízí vynikající spojení s okolními městy.
Sandhausen se nachází přibližně osm kilometrů jižně od Heidelbergu a je součástí metropolitní oblasti Rýn-Neckar.
Obec svým přibližně 15 000 obyvatelům nabízí veškeré vybavení pro každodenní život, včetně obchodů, gastronomických zařízení, zdravotní péče a lékáren. K dispozici je řada mateřských škol a škol, stejně jako bohatý klubový život a rozličné sportovní a volnočasové aktivity pro různé zájmy.
Dopravní spojení veřejnou dopravou je velmi dobré. Nádraží St. Ilgen/Sandhausen nabízí přímé spoje do Heidelbergu, Mannheimu a Karlsruhe. Do Heidelbergu se dá dostat autem i veřejnou dopravou přibližně za 15 minut a dálnice A5 je vzdálena cca 10 minut jízdy.,

Description_in_english: nan

# Discussion
It seems that there is some intelligence in the match - only one match is from CZ, the rest are from Germany.

Let's try to make a clear query

### Clear query

In [20]:
representation = "3+1 byt k pronájmu Praha, 15000 CZK, rekonstruovaný, rent, Czech Republic, Prague"

res = requests.post('http://localhost:11434/api/embeddings',
                    json={
                        'model': 'nomic-embed-text',
                        'prompt': representation
                    }
                   )

embedding = np.array([res.json()['embedding']], dtype = 'float32')

D, I = index.search(embedding, 10)

best_matches = np.array(df['textual_representation'])[I.flatten()]

for match in best_matches[1:]: # skip the first (it's identical to the query)
    print('NEXT PROPERTY')
    print(match)
    print()

NEXT PROPERTY
 Title: Pronájem bytu • 80 m² bez realitky Pštrossova, Praha - Nové Město,
Price: 112041.0 CZK,

Description_in_native: nan,

Description_in_english: Unique 3-bedroom apartment by the National theater. Luxury Pštrossova apartment for rent just a few steps from Wenceslas Square. Renovated apartment in the very center of Prague.
IMPORTANT INFORMATION!
Please be advised that due to legal regulations we are required to register you with the foreign police and collect city tax upon your arrival.
The city tax is 2,10 EUR per person per day. Children under 18 and people from Prague do not pay this fee.
Living in this area offers many cultural activities, as well as easy access to public transport and walking distance to many shops (Quadrio), theaters and cinemas. A few meters from the apartment there is the Můstek and Národní třída metro station.
The apartment consists of:
-Fast Wi-Fi
-Kitchen with full equipment
-3 Bathrooms
-3 Bedrooms

NEXT PROPERTY
 Title: Pronájem bytu 3+1 • 105 m² bez realitky Heřmanova, Praha - Holešovice,
Price: 35000.0 CZK,

Description_in_native: Prostorný byt 3+1 (120m2) na Letné
K dlouhodobému pronájmu nabízíme byt na Letné (Heřmanova na úrovni Kamenické), 3+1, 120 m2, přímo od majitele.
Byt se skládá ze tří neprůchozích pokojů, obývák (36m2), ložnice s balkónkem, kuchyň s novou linkou a spíž,  prostorná koupelna s WC  a samostatné WC. Vysoké stropy (3,4 m), eurookna, etážové topení s vlastním plynovým kotlem. Byt se nachází v prvním patře hezkého činžovního domu bez výtahu. K bytu lze pronajmout garáž či parkovací stání ve dvoře domu za příplatek. K bytu patří sklep za příplatek.
Měsíční poplatek za služby a paušál vodného, stočného je účtován na osobu.
K dispozici ihned.
Prosíme, aby nás nekontaktovaly realitní kanceláře.,

Description_in_english: Spacious 3+1 Apartment (120m²) in Letná
For long-term rental, we offer an apartment in Letná (Heřmanova at the Kamenická level), 3+1, 120 m², directly from the owner.
The apartment consists of three non-connecting rooms, a living room (36 m²), a bedroom with a small balcony, a kitchen with a new unit and a pantry, a spacious bathroom with a toilet, and a separate toilet. It features high ceilings (3.4 m), Euro-style windows, and district heating with its own gas boiler. The apartment is located on the first floor of a nice tenement house without an elevator. A garage or a parking space in the courtyard of the building can be rented as an extra option. A cellar is available as an extra option.
The monthly service fee and flat rate for water and sewage are charged per person.
Available immediately.
Please, no contact from real estate agencies.

NEXT PROPERTY
 Title: Prodej bytu 3+1 • 72 m² bez realitky Vöcklamarkt Oberösterreich 4870,
Price: 187000.0 EUR,

Description_in_native: 3-pokojový byt s loggií a krbem
Infrastruktura / vzdálenosti
Zdraví
Lékař,

Description_in_english: nan

NEXT PROPERTY
 Title: Pronájem bytu • 101 m² bez realitky Dlouhá, Praha - Staré Město,
Price: 74357.0 CZK,

Description_in_native: nan,

Description_in_english: Blueground | Prague 1, furnished, Old town ID43. This spacious 3kk apartment is located on Dlouhá Třída in Prague’s Old Town, one of the city’s most historic and dynamic neighborhoods. Just steps away from the Vltava River, trendy cafés, cultural landmarks, and boutique shops, it offers the perfect base for both everyday living and exploring the city. (ID #PRG43)
Designed with you in mind
The apartment blends original architectural features with a clean, modern design. With generous living space and two bright bedrooms, it includes a fully equipped kitchen, cozy living area, and a dedicated workspace — ideal for couples, professionals, or small families staying mid-term in Prague.
Why choose Blueground
We offer thoughtfully furnished, move-in ready apartments in hand-picked locations. Every home includes a fully equipped kitchen, hotel-quality linens, high-speed Wi-Fi, and everything needed for a seamless stay — whether it’s for one month or longer.
Transportation
Tram: Just a 1-minute walk to Dlouhá Třída tram stop, with direct lines to Letná Park, Karlín, and Žižkov.
Metro: A 7-minute walk to Náměstí Republiky station (yellow line B), offering fast connections across central Prague and beyond.

NEXT PROPERTY
 Title: Pronájem bytu 4+kk • 109 m² bez realitky Walterovo náměstí, Praha - Jinonice,
Price: 45900.0 CZK,

Description_in_native: New 4 room apartment to rent in Prague 5 at Metro B. The modern residential complex of Rezidence Waltrovka offers a wide variety of public services along with extensive green areas, including several children’s playgrounds. The apartment is situated on the 6th floor and occupies 99,1 m2. Moreover, 2 balconies (6,0 m2 +3,8 m2) provide a beautiful view at the neighboring areas. The calm location of Prague 5, just 5 minutes on foot to the metro station Jinonice, combines the advantages of the relaxed family life with the excellent connection to the city center. In the neighborhood, you can also find the commercial center Andel, international schools, several sporting facilities as well as natural parks of Vidoule and Prokopske udoly.
The apartment consists of a living room with fully equipped kitchen, 3 separate bedrooms, a bathroom, a toilet and an extensive corridor with a wardrobe. The balconies are accessible from the living room and one of the bedrooms.
Wooden floors, tiles, security entrance doors, large windows, dishwasher, cellar, common garden and childrens playground near the house provide additional comfort.
The apartment is available for CZK 45.900 per month. Service charges of CZK 7.200 per month (water, heating, cleaning and maintenance of common areas). Electricity will be transferred to the lessee. The apartment is being rented together with a parking space in the underground garage. There is no commission to a real estate broker. Available from July 1, 2026. We prefer tenants with a minimal rental period of 2 years.,

Description_in_english: Nový, moderní byt 4+kk k pronájmu na Praze 5, přímo na metru B. Moderní čtvrť Rezidence Waltrovka nabízí bohatou občanskou vybavenost s rozsáhlými plochami zeleně, včetně několika dětských hřišť. Byt o celkové podlahové ploše 99,1 m2 se 2 lodžiemi (6,0 m2 +3,8 m2) a nádherným výhledem do okolí je situován v 6. poschodí. Lokalita v klidné části Prahy 5, pouhých 5 minut chůze od stanice metra Jinonice, kombinuje výhody klidného rezidenčního bydlení s absolutní blízkostí centra města. V blízkém dosahu se nachází komerční centrum Anděl, Francouzské a Německé mezinárodní školy, sportovní zařízení a přírodní parky Vidoule a Prokopské údolí.
Interiér bytu tvoří 3 samostatné ložnice, obývací pokoj s plně vybavenou kuchyní, koupelna s vanou, toaleta, šatna a prostorná vstupní hala. Balkony jsou přístupné z obývacího pokoje a jedné z ložnic. Dřevěné podlahy, dlažba, bezpečnostní vstupní dveře, velká okna, myčka, sklep, společná zahrada a dětské hřiště v blízkosti domu.
Byt se pronajímá za 45.900 Kč/měs. Poplatky za služby zálohově ve výši 7.200 Kč/měs (voda, teplo, úklid společných prostor a domovní služby). Elektřina bude převedena na nájemce. K bytu patří garážové stání v podzemní garáži. Neplatíte žádnou provizi RK. K nastěhování od 1.7.2029. Upřednostňujeme zájemce s minimální dobou nájmu 2 let.

NEXT PROPERTY
 Title: Pronájem bytu 3+kk • 400 m² bez realitky Merhautova, Brno - Černá Pole, Jihomoravský kraj,
Price: 69000.0 CZK,

Description_in_native: Nabízím k pronájmu luxusní Penthouse - triplex (třípatrový byt) v  3-5 NP s panoramatických výhledem na celé Brno. Architekt nechal vyniknout výhled v každé místnosti a doplnil jej čistými liniemi kovu, skla a kamene. Atmosféru a charakter bytu dokreslují designové prvky a promyšlené několika úrovňové osvětlení. Penthouse je plně zařízen luxusním nábytkem.
Lokalita Brno-Černá Pole. Vnitřní plocha 250 m2, terasy 150 m2. Celková plocha 400 m2. V ceně bytu je výlučné užívání 2 parkovacích stání před domem. V okolí veškerá občanská vybavenost. Rezidenční lokalita včetně parků. Dostupnost centra 5 min.
Je požadována vratná kauce ve výši 200 000 Kč.
Tato indikativní nabídka není nabídkou ve smyslu § 1731 nebo § 1732 občanského zákoníku. Z této indikativní nabídky nevzniká nárok na uzavření žádné smlouvy.
Pronajímatel si vyhrazuje právo vybrat nájemce na základě jím zvolených kritérií,

Description_in_english: We rent three-storey luxury penthouse in a 3-5 floors with panoramic views across Brno. Penthouse is fully furnished. Location Brno-Černá Pole. Interior of 250 m2, exterier 3 terraces 150 m2. Total space 400 m2. The apartment is rented with 2 parking places. More information on request.
All civic amenities. Availability town center 5 min. tram.
Is required refundable deposit 150 000 CZK.

NEXT PROPERTY
 Title: Pronájem bytu 3+kk • 100 m² bez realitky Čáslavská, Praha - Vinohrady,
Price: 28000.0 CZK,

Description_in_native: Pronájem bytu 3+kk (100 m2) přímo u metra Flora – Vinohrady (Bez provize) Nabízím k pronájmu prostorný byt 3+kk o velikosti 100 m2 v v prestižní lokalitě pražských Vinohrad, v ulici Čáslavská. Byt se nachází v prvním patře udržovaného činžovního domu s výtahem, jen 2 minuty chůze od metra A a nákupního centra Flora. Dispozice bytu: • Obývací pokoj: Prostorná místnost s arkýřem orientovaná do ulice, která bytu dodává jedinečnou atmosféru. • Pokoj s kuchyňským koutem: Slouží jako jídelna či společenská místnost, vybavená linkou s vestavnými spotřebiči (myčka, plynová varná deska, elektrická trouba). • Ložnice: Samostatný, neprůchozí pokoj orientovaný do klidného vnitrobloku se zelení a hřištěm. • Hala: Centrální prostor bytu s instalovanou prostornou skříňovou stěnou, která zajišťuje dostatek úložného místa. • Příslušenství: Předsíň, praktická spíž u kuchyně, koupelna s vanou a samostatné WC. Většina oken směřuje do klidného, veřejně přístupného vnitrobloku s dětským hřištěm. Vytápění je zajištěno plynovými topidly (vafky), ohřev vody elektrickým bojlerem. V bytě je instalován videotelefon a společné prostory jsou monitorovány kamerovým systémem. Lokalita a občanská vybavenost: Perfektní dopravní dostupnost (metro, tramvaje, autobus) a veškerá vybavenost v místě (obchody, restaurace, školy, parky). Vnitroblok je přístupný z ulic Vinohradská a Slezská. Koho hledáme: Byt je ideální pro pár nebo menší tříčlennou rodinu. Hledáme nájemníky, kteří jsou nekuřáci a bez zvířecích mazlíčků. Finanční podmínky: • Měsíční nájemné: 28.000 Kč • Poplatky za služby: 1.500 Kč (včetně vody za 2 osoby, každá další osoba + 500 Kč) • Zálohy na plyn a elektřinu: 3.500 Kč • Kauce: 56.000 Kč (dva měsíční nájmy) • Provize: 0 Kč (pronajímá přímý majitel) Byt je volný a připraven k nastěhování. V případě zájmu o prohlídku mě prosím kontaktujte.,

Description_in_english: Rental of a 3+kk Apartment (100 m²) Right by Metro Flora – Vinohrady (No Commission)
I am offering for rent a spacious 3+kk apartment (100 m²) in the prestigious Prague Vinohrady district, located on Čáslavská Street. The apartment is situated on the first floor of a well-maintained building with an elevator, just a 2-minute walk from Metro Line A and the Flora shopping center.
Apartment Layout:
• Living Room: A spacious room with an alcove facing the street, which gives the apartment its unique atmosphere.
• Room with Kitchenette: Functions as a dining or living room area, equipped with a storeroom and built-in appliances (dishwasher, gas hob, electric oven).
• Bedroom: A separate, non-connecting room facing a quiet inner courtyard with greenery and a playground.
• Hallway: The central area of the apartment featuring a large built-in wardrobe, ensuring ample storage space.
• Additional Features: An entrance hall, a practical storeroom adjacent to the kitchen, a bathroom with a bathtub, and a separate toilet.
Most windows overlook a quiet, publicly accessible inner courtyard with a children's playground. Heating is provided by gas heaters (waw) and water is heated by an electric boiler. The apartment is equipped with a videophone, and the common areas are monitored by a camera system.
Location and Amenities:
Perfect transportation connections (metro, trams, buses) and complete local amenities (shops, restaurants, schools, parks). The inner courtyard is accessible from both Vinohradská and Slezská streets.
Who We Are Looking For:
The apartment is ideal for a couple or a small three-person family. We are seeking tenants who are non-smokers and do not have pets.
Financial Terms:
• Monthly Rent: 28,000 CZK
• Service Charges: 1,500 CZK (including water for 2 people; each additional person +500 CZK)
• Deposits for Gas and Electricity: 3,500 CZK
• Security Deposit: 56,000 CZK (equivalent to two months’ rent)
• Commission: 0 CZK (rented directly by the owner)
The apartment is available and ready for move-in. If you are interested in scheduling a visit, please contact me.

NEXT PROPERTY
 Title: Prodej bytu 3+1 • 140 m² bez realitky Alfred-Kowalke-Str.14 Berlin Friedrichsfelde Berlin 10315,
Price: 475000.0 EUR,

Description_in_native: Diese außergewöhnlich großzügige Eigentumswohnung befindet sich im 1. Obergeschoss eines gepflegten Mehrfamilienhauses (Baujahr 1997) in attraktiver Lage von Berlin-Friedrichsfelde. Mit einer Wohnfläche von ca. 140 m² zählt sie zu den seltenen Angeboten ihrer Art und überzeugt durch hochwertige Ausstattung, sehr guten Pflegezustand und eine gute energetische Bilanz.
Tato výjimečně prostorná vlastnická byty se nachází v prvním nadzemním podlaží udržovaného rodinného domu (rok výstavby 1997) v atraktivní lokalitě v berlínském čtvrti Friedrichsfelde. S obytnou plochou zhruba 140 m² patří k vzácným nabídkám svého druhu a zaujme vysokou úrovní vybavení, výborným stavem údržby a dobrou energetickou bilancí.
Die Wohnung wurde frisch renoviert und ist sofort bezugsfertig. Aktuell als 3-Zimmer-Wohnung genutzt, bietet sie eine optionale Erweiterungsmöglichkeit, wodurch sie sich flexibel an individuelle Wohnkonzepte anpassen lässt – ideal für Eigennutzer mit Anspruch oder als wertstabile Kapitalanlage in Berlin.
Byt byl čerstvě zrenovován a je ihned k nastěhování. V současnosti slouží jako 3-pokojový byt, má však možnost rozšíření, díky čemuž se dá flexibilně přizpůsobit individuálním představám o bydlení – ideální pro náročné uživatele nebo jako stabilní investice v Berlíně.
Der lichtdurchflutete Wohnbereich mit direktem Zugang zur sonnigen Süd-Balkonterrasse bildet das Herzstück der Wohnung. Hochwertiger Parkettboden, neu geschliffen und versiegelt, verleiht den Räumen eine elegante Atmosphäre. Die neue Einbauküche sowie das sanierte Badezimmer mit moderner Dusche unterstreichen den gehobenen Wohnkomfort.
Světlem zalitá obývací část s přímým vstupem na slunnou jižní balkonovou terasu tvoří srdce bytu. Kvalitní parketová podlaha, čerstvě přebrýchaná a natěrná, dodává místnostem elegantní vzhled. Nově zařízená kuchyňská linka a zrekonstruovaná koupelna s moderní sprchou ještě více podtrhují komfort vysoce kvalitního bydlení.
Ein Tiefgaragenstellplatz sorgt für bequemes Parken. Zusätzlich steht ein ca. 10 m² großes, trockenes und sauberes Kellerabteil im Dachboden zur Verfügung – ein praktischer Mehrwert.
Podzemní garážové stání zajišťuje pohodlné parkování. Navíc je k dispozici přibližně 10 m² velký, suchý a čistý sklepní prostor v podkroví – praktická přidaná hodnota.
Die Lage in Berlin-Friedrichsfelde (Lichtenberg) überzeugt durch eine sehr gute Infrastruktur, ruhiges Wohnen und eine hervorragende Anbindung an den öffentlichen Nahverkehr.
Lokalita v berlínském Friedrichsfelde (Lichtenberg) zaujme velmi dobrou infrastrukturou, klidným bydlením a výborným spojením s městskou hromadnou dopravou.
Lage & Verkehrsanbindung – Berlin-Friedrichsfelde
Lokalita a dopravní spojení – Berlín-Friedrichsfelde
Die Immobilie überzeugt durch eine herausragende Verkehrsanbindung sowie eine exzellente Infrastruktur – ideal für anspruchsvolle Stadtbewohner, Pendler und Kapitalanleger.
Nemovitost zaujme vynikajícím dopravním spojením i špičkovou infrastrukturou – ideální pro náročné městské obyvatele, dojíždějící i investory.
U-Bahn Tierpark: ca. 300 m Fußweg
Metro u Tierparku: cca 300 m pěšky
U-Bahn Friedrichsfelde: ca. 250 m Fußweg
Metro u Friedrichsfelde: cca 250 m pěšky
S-Bahn Karlshorst mit Regionalbahnanschluss und direkter Verbindung in die Berliner City
Regionální vlak S-Bahn Karlshorst s přímým spojením do berlínského centra
S-Bahn Friedrichsfelde-Ost: ca. 500 m entfernt, erreichbar in 1 Tramstation
S-Bahn Friedrichsfelde-Ost: cca 500 m, dosažitelné jednou zastávkou tramvaje
Tramlinie M17 mit durchgehendem Nachtbetrieb
Tramvajová linka M17 s nepřetržitým nočním provozem
B1 / B5: schnelle Anbindung in das östliche Berliner Umland sowie direkt Richtung Alexanderplatz
Silniční spojení B1 / B5: rychlé spojení do východního okolí Berlína i přímo směrem na Alexanderplatz
️ Infrastruktur & Versorgung
Infrastruktura a občanská vybavenost
Einkaufsmöglichkeiten und Dienstleistungen des täglichen Bedarfs befinden sich in unmittelbarer fußläufiger Umgebung:
Nákupní možnosti a služby denní potřeby se nachází v bezprostřední pěší vzdálenosti:
Einkaufszentrum
Nákupní centrum
Supermärkte
Supermarkety
Ärzte & Apotheken
Doktoři a lékárny
Wochenmarkt
Týdenní trh
Freizeit & Naherholung
Volný čas a rekreace
Die Lage bietet zudem einen außergewöhnlich hohen Freizeit- und Erholungswert:
Lokalita navíc nabízí mimořádně vysoký potenciál pro volnočasové aktivity a odpočinek:
Tierpark Berlin
Berlínská ZOO/Tierpark
Biesdorfsee
Jezero Biesdorf
Wuhlheide
Wuhlheide (lesní a rekreační oblast)
Große Park- und Grünflächen – ideal für Naturliebhaber, Jogger und Erholungssuchende
Rozsáhlé parky a zelené plochy – ideální pro milovníky přírody, běžce i ty, kteří hledají odpočinek
Kontakt & Besichtigung
Kontakt a prohlídka
Dieses Angebot richtet sich an Käufer mit Anspruch.
Vážená nabídka je určena pro náročné kupce.
Vereinbaren Sie jetzt einen persönlichen Besichtigungstermin und sichern Sie sich diese provisionsfreie Gelegenheit in Berlin-Friedrichsfelde.
Domluvte si nyní osobní prohlídku a zajišťujte si tuto příležitost bez provize v Berlín-Friedrichsfelde.
Wir freuen uns auf Ihre Kontaktaufnahme.
Těšíme se na Vaši zprávu.
Haftungsa­usschluss
Odškodnění a vyloučení odpovědnosti
Alle Angaben in diesem Exposé beruhen auf Informationen des Eigentümers.
Veškeré údaje v tomto propagačním materiálu jsou založeny na informacích poskytnutých vlastníkem.
Für die Richtigkeit, Vollständigkeit und Aktualität der Angaben zu Flächen, Maßen, Preisen und Ausstattungsmerkmalen wird keine Haftung oder Gewähr übernommen.
Na správnost, úplnost a aktuálnost údajů o plochách, rozměrech, cenách a charakteristikách vybavení není poskytována žádná odpovědnost ani záruka.
Dargestellte Innenausstattungen, Möblierungen und Außenansichten dienen ausschließlich der unverbindlichen Veranschaulichung.
Zobrazené interiérové vybavení, zařizování a exteriérové pohledy slouží výhradně k orientačnímu účelu.,

Description_in_english: nan

NEXT PROPERTY
 Title: Pronájem bytu 3+kk • 87 m² bez realitky Preslova, Praha - Smíchov,
Price: 32200.0 CZK,

Description_in_native: Pronájem bytu 3+kk v lokalitě Praha 5 – Anděl. Byt má dispozici 3+kk – obývací pokoj s kuchyňským koutem a dvě samostatné, neprůchozí ložnice. K dispozici je koupelna a samostatné WC. Byt se nachází v blízkosti metra Anděl a tramvajových zastávek, s výbornou dostupností do centra města. V okolí je kompletní občanská vybavenost – obchody, restaurace, kavárny a nákupní centrum. Elektřina a plyn se převádějí na nájemce.,


# Discussion
The third match looks completely random.

Let's see if query format affects the search.

## Query format

In [33]:
representation = "3+1 byt k pronájmu Praha, 15000 CZK, rekonstruovaný, rent, Czech Republic, Prague"

res = requests.post('http://localhost:11434/api/embeddings',
                    json={'model': 'nomic-embed-text', 'prompt': representation})
query_embedding = np.array(res.json()['embedding'], dtype='float32').reshape(1, -1)

D, I = index.search(query_embedding, k=5)
print(D)

[[185.6018  215.19856 218.41849 221.16122 224.54181]]

In [34]:
representation = """Title: Pronájem bytu 3+1, Praha,
Price: 15000 CZK,
Description_in_english: 2 bedroom apartment for rent in Prague, renovated, close to metro, parking available"""

res = requests.post('http://localhost:11434/api/embeddings',
                    json={'model': 'nomic-embed-text', 'prompt': representation})
query_embedding = np.array(res.json()['embedding'], dtype='float32').reshape(1, -1)

D, I = index.search(query_embedding, k=5)
print(D)

[[137.78725 138.3623  140.6383  141.6314  142.3622 ]]

# Discussion
It seems that proper query format improves the search, but not sure if this is a valid way to interpret it.

Maybe descriptions confuse the embedding model. Maybe we should test this on a alza dataset which is way 
more structured.